import { StyleSheet, Dimensions } from 'react-native';
import { scale } from '../utils/responsive';

const { width, height } = Dimensions.get('window');

export const Color = {
  primary: '#40B649',
  blue: '#50A8FF',
  gray: '#D9D9D9',
  black: '#000000',
  white: '#FFFFFF',
}


export const commonStyle = StyleSheet.create({
  mt1: { marginTop: scale(1) },
  mt2: { marginTop: scale(2) },
  mt3: { marginTop: scale(3) },
  mt4: { marginTop: scale(4) },
  mt5: { marginTop: scale(5) },
  mt10: { marginTop: scale(10) },
  mt15: { marginTop: scale(15) },
  mt20: { marginTop: scale(20) },
  mt25: { marginTop: scale(25) },
  mt30: { marginTop: scale(30) },
  mt35: { marginTop: scale(35) },
  mt40: { marginTop: scale(40) },
  mt45: { marginTop: scale(45) },
  mt50: { marginTop: scale(50) },
  mt55: { marginTop: scale(55) },
  mt60: { marginTop: scale(60) },
  mt65: { marginTop: scale(65) },
  mt70: { marginTop: scale(70) },
  mb5: { marginBottom: scale(5) },
  mb10: { marginBottom: scale(10) },
  mb15: { marginBottom: scale(15) },
  mb20: { marginBottom: scale(20) },
  mb25: { marginBottom: 25 },
  mb30: { marginBottom: scale(30) },
  mb40: { marginBottom: scale(40) },
  mb50: { marginBottom: scale(50) },
  mb60: { marginBottom: scale(60) },
  mb70: { marginBottom: scale(70) },
  ml5: { marginLeft: scale(5) },
  ml10: { marginLeft: scale(10) },
  ml15: { marginLeft: scale(15) },
  ml20: { marginLeft: scale(20) },
  ml25: { marginLeft: scale(25) },
  ml30: { marginLeft: scale(30) },
  mr5: { marginRight: scale(5) },
  mr8: { marginRight: scale(8) },
  mr10: { marginRight: scale(10) },
  mr15: { marginRight: scale(15) },
  mr20: { marginRight: scale(20) },
  mr25: { marginRight: scale(25) },
  mr30: { marginRight: scale(30) },
  mr40: { marginRight: scale(40) },
  mr50: { marginRight: scale(50) },
  mr60: { marginRight: scale(60) },
  mr70: { marginRight: scale(70) },
  mr80: { marginRight: scale(80) },
  mr90: { marginRight: scale(90) },
  mr100: { marginRight: scale(100) },
  mr110: { marginRight: scale(110) },
  mr120: { marginRight: scale(120) },
  mr130: { marginRight: scale(130) },
  mr140: { marginRight: scale(140) },
  mr150: { marginRight: scale(150) },
  pt5: { paddingTop: scale(5) },
  pt10: { paddingTop: scale(10) },
  pt15: { paddingTop: scale(15) },
  pt20: { paddingTop: scale(20) },
  pt25: { paddingTop: scale(25) },
  pt30: { paddingTop: scale(30) },
  pt50: { paddingTop: scale(50) },
  pt70: { paddingTop: scale(70) },
  pb5: { paddingBottom: scale(5) },
  pb10: { paddingBottom: scale(10) },
  pb15: { paddingBottom: scale(15) },
  pb20: { paddingBottom: scale(20) },
  pb25: { paddingBottom: 25 },
  pb30: { paddingBottom: scale(30) },
  pb40: { paddingBottom: scale(40) },
  pb50: { paddingBottom: scale(50) },
  pb60: { paddingBottom: scale(60) },
  pb70: { paddingBottom: scale(70) },
  pl5: { paddingLeft: scale(5) },
  pl10: { paddingLeft: scale(10) },
  pl15: { paddingLeft: scale(15) },
  pl20: { paddingLeft: scale(20) },
  pl25: { paddingLeft: scale(25) },
  pl30: { paddingLeft: scale(30) },
  pr5: { paddingRight: scale(5) },
  pr8: { paddingRight: scale(8) },
  pr10: { paddingRight: scale(10) },
  pr15: { paddingRight: scale(15) },
  pr20: { paddingRight: scale(20) },
  pr25: { paddingRight: scale(25) },
  pr30: { paddingRight: scale(30) },
  fontSize10: { fontSize: scale(10) },
  fontSize11: { fontSize: scale(11) },
  fontSize12: { fontSize: scale(12) },
  fontSize13: { fontSize: scale(13) },
  fontSize14: { fontSize: scale(14) },
  fontSize15: { fontSize: scale(15) },
  fontSize16: { fontSize: scale(16) },
  fontSize17: { fontSize: scale(17) },
  fontSize18: { fontSize: scale(18) },
  fontSize20: { fontSize: scale(20) },
  fontSize22: { fontSize: scale(22) },
  fontSize25: { fontSize: scale(25) },
  textCenter: { textAlign: 'center' },
  textLeft: { textAlign: 'left' },
  textRight: { textAlign: 'right' },
  width100: { width: '100%' },
  ph5: {paddingHorizontal : scale(5)},
  ph10: {paddingHorizontal : scale(10)},
  ph11: {paddingHorizontal : scale(11)},
  ph12: {paddingHorizontal : scale(12)},
  ph13: {paddingHorizontal : scale(13)},
  ph14: {paddingHorizontal : scale(14)},
  ph15: {paddingHorizontal : scale(15)},
  ph16: {paddingHorizontal : scale(16)},
  ph17: {paddingHorizontal : scale(17)},
  ph18: {paddingHorizontal : scale(18)},
  ph19: {paddingHorizontal : scale(19)},
  ph20: {paddingHorizontal : scale(20)},
  ph21: {paddingHorizontal : scale(21)},
  ph22: {paddingHorizontal : scale(22)},
  ph23: {paddingHorizontal : scale(23)},
  ph24: {paddingHorizontal : scale(24)},
  ph25: {paddingHorizontal : scale(25)},
  ph26: {paddingHorizontal : scale(26)},
  ph27: {paddingHorizontal : scale(27)},
  ph28: {paddingHorizontal : scale(28)},
  ph29: {paddingHorizontal : scale(29)},
  ph30: {paddingHorizontal : scale(30)},
  ph35: {paddingHorizontal : scale(35)},
  ph40: {paddingHorizontal : scale(40)},
  ph50: {paddingHorizontal : scale(50)},
  ph60: {paddingHorizontal : scale(60)},
  ph70: {paddingHorizontal : scale(70)},
  pv5: {paddingVertical : scale(5)},
  pv10: {paddingVertical : scale(10)},
  pv11: {paddingVertical : scale(11)},
  pv12: {paddingVertical : scale(12)},
  pv13: {paddingVertical : scale(13)},
  pv14: {paddingVertical : scale(14)},
  pv15: {paddingVertical : scale(15)},
  pv16: {paddingVertical : scale(16)},
  pv17: {paddingVertical : scale(17)},
  pv18: {paddingVertical : scale(18)},
  pv19: {paddingVertical : scale(19)},
  pv20: {paddingVertical : scale(20)},
  pv21: {paddingVertical : scale(21)},
  pv22: {paddingVertical : scale(22)},
  pv23: {paddingVertical : scale(23)},
  pv24: {paddingVertical : scale(24)},
  pv25: {paddingVertical : scale(25)},
  pv26: {paddingVertical : scale(26)},
  pv27: {paddingVertical : scale(27)},
  pv28: {paddingVertical : scale(28)},
  pv29: {paddingVertical : scale(29)},
  pv30: {paddingVertical : scale(30)},
  pv35: {paddingVertical : scale(35)},
  pv40: {paddingVertical : scale(40)},
  pv50: {paddingVertical : scale(50)},
  pv60: {paddingVertical : scale(60)},
  pv70: {paddingVertical : scale(70)},
  mv5: {marginVertical : scale(5)},
  mv10: {marginVertical : scale(10)},
  mv15: {marginVertical : scale(15)},
  mv20: {marginVertical : scale(20)},
  mv25: {marginVertical : scale(25)},
  mv30: {marginVertical : scale(30)},
  mv40: {marginVertical : scale(40)},
  mv50: {marginVertical : scale(50)},
  mv60: {marginVertical : scale(60)},
  mv70: {marginVertical : scale(70)},
  mv80: {marginVertical : scale(80)},
  mv90: {marginVertical : scale(90)},
  mv100: {marginVertical : scale(100)},
  mv110: {marginVertical : scale(110)},
  mv120: {marginVertical : scale(120)},
  mv130: {marginVertical : scale(130)},
  mv140: {marginVertical : scale(140)},
  hipSlop5: {top: scale(5), bottom: scale(5), left: scale(5), right: scale(5)},
  hipSlop10: {top: scale(10), bottom: scale(10), left: scale(10), right: scale(10)},
  hipSlop15: {top: scale(15), bottom: scale(15), left: scale(15), right: scale(15)},
  hipSlop20: {top: scale(20), bottom: scale(20), left: scale(20), right: scale(20)},
  hipSlop25: {top: scale(25), bottom: scale(25), left: scale(25), right: scale(25)},
  hipSlop30: {top: scale(30), bottom: scale(30), left: scale(30), right: scale(30)},
});

// 유틸리티 함수들
export const iconSquareSize = (size: number) => {
  return {
    width: size,
    height: size,
  };
};

export const styles = StyleSheet.create({
  bgColorGray: {
    backgroundColor: Color.black,
  },
  iconSize: {
    width: scale(8.4),
    height: scale(15.3),
    resizeMode: 'contain',
  },  
  iconSize16: {
    width: scale(16),
    height: scale(16),
  },
  iconSize18: {
    width: scale(18),
    height: scale(18),
  },
  iconSize20: {
    width: scale(20),
    height: scale(20),
  },
  iconSize22: {
    width: scale(22),
    height: scale(22),
  },
  iconSize24: {
    width: scale(24),
    height: scale(24),
  },
  iconSize32: {
    width: scale(32),
    height: scale(32),
  },
  iconSize40: {
    width: scale(40),
    height: scale(40),
  },
  iconSize48: {
    width: scale(48),
    height: scale(48),
  },
  iconSize60: {
    width: scale(60),
    height: scale(60),
  },
  iconSize65: {
    width: scale(65),
    height: scale(65),
  },
  iconSize70: {
    width: scale(70),
    height: scale(70),
  },
  iconSize80: {
    width: scale(80),
    height: scale(80),
  },
});

export const layoutStyle = StyleSheet.create({
  flex1: { flex: 1 },
  row: { flexDirection: 'row' },
  alignCenter: { alignItems: 'center' },
  alignStart: { alignItems: 'flex-start' },
  alignEnd: { alignItems: 'flex-end' },
  justifyCenter: { justifyContent: 'center' },
  justifyBetween: { justifyContent: 'space-between' },
  justifyStart: { justifyContent: 'flex-start' },
  justifyEnd: { justifyContent: 'flex-end' },
  selfEnd: { alignSelf: 'flex-end' },
  selfStart: { alignSelf: 'flex-start' },
  wrap: { flexWrap: 'wrap' },
  noWrap: { flexWrap: 'nowrap' },
  columnStart: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  columnStretchEvenly: {
    flexDirection: 'column',
    alignSelf: 'stretch',
    justifyContent: 'space-evenly',
  },
  columCenter: { alignItems: 'center', justifyContent: 'center' },
  rowCenter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowStart: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  rowEnd: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rowAlignStart: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  textCenter: { textAlign: 'center' },
  textLeft: { textAlign: 'left' },
  textRight: { textAlign: 'right' },
  lineFontGray: { textDecorationLine: 'underline' },
});