// 앱에서 사용하는 모든 이미지 리소스를 중앙에서 관리합니다.
const IMAGES = {
  icons: {
    // 아이콘 이미지
    arrowDownWhite: require('../assets/images/icon/icon_arrow_down_white.png'),
    arrowLeftWhite: require('../assets/images/icon/icon_arrow_left_white.png'),
    arrowRightWhite: require('../assets/images/icon/icon_arrow_right_white.png'),
    arrowLeftBlack: require('../assets/images/icon/icon_arrow_left_black.png'),
    arrowLeftGray: require('../assets/images/icon/icon_arrow_left_gray.png'),
    arrowDownGray: require('../assets/images/icon/icon_arrow_down_gray.png'),
    arrowUpGray: require('../assets/images/icon/icon_arrow_up_gray.png'),
    barWhite: require('../assets/images/icon/icon_bar_white.png'),
    bellWhite: require('../assets/images/icon/icon_bell_white.png'),
    bellAlamWhite: require('../assets/images/icon/icon_bell_alam_white.png'),
    calendarGray: require('../assets/images/icon/icon_calendar_gray.png'),
    calendarGreen: require('../assets/images/icon/icon_calendar_green.png'),
    cartGray: require('../assets/images/icon/icon_cart_gray.png'),
    cartGreen: require('../assets/images/icon/icon_cart_green.png'),
    clockGray: require('../assets/images/icon/icon_clock_gray.png'),
    clockGreen: require('../assets/images/icon/icon_clock_green.png'),
    editCircleBlue: require('../assets/images/icon/icon_edit_circle_blue.png'),
    exclamationMarkRed: require('../assets/images/icon/icon_exclamation_mark_red.png'),
    fireWhite: require('../assets/images/icon/icon_fire_white.png'),
    heartGreen: require('../assets/images/icon/icon_heart_green.png'),
    homeGray: require('../assets/images/icon/icon_home_gray.png'),
    homeWhite: require('../assets/images/icon/icon_home_white.png'),
    profileGray: require('../assets/images/icon/icon_profile_gray.png'),
    profileGreen: require('../assets/images/icon/icon_profile_green.png'),
    runWhite: require('../assets/images/icon/icon_run_white.png'),
    heartWhite: require('../assets/images/icon/icon_heart_white.png'),
    arrowLeftFullWhite: require('../assets/images/icon/icon_arrow_left_full_white.png'),
    arrowRightFullWhite: require('../assets/images/icon/icon_arrow_right_full_white.png'),
    arrowLeftFullGray: require('../assets/images/icon/icon_arrow_left_full_gray.png'),
    arrowRightFullGray: require('../assets/images/icon/icon_arrow_right_full_gray.png'),
    xWhite: require('../assets/images/icon/icon_x_white.png'),
    garbageRed: require('../assets/images/icon/icon_garbage_red.png'),
    pictureWhite: require('../assets/images/icon/icon_picture_white.png'),
    checkGray: require('../assets/images/icon/icon_circle_check_gray.png'),
    checkGreen: require('../assets/images/icon/icon_circle_check_green.png'),
    smallBarGray: require('../assets/images/icon/icon_small_bar_gray.png'),
    arrowRightGray: require('../assets/images/icon/icon_arrow_right_gray.png'),
    shopHomeGray: require('../assets/images/icon/icon_shop_home_gray.png'),
    shopHeartGray: require('../assets/images/icon/icon_shop_heart_gray.png'),
    shopSearchGray: require('../assets/images/icon/icon_shop_search_gray.png'),
    shopMyPageGray: require('../assets/images/icon/icon_shop_my_gray.png'),
    shopHomeFillGray: require('../assets/images/icon/icon_shop_home_gray_fill.png'),
    shopHeartFillGray: require('../assets/images/icon/icon_shop_heart_gray_fill.png'),
    shopSearchFillGray: require('../assets/images/icon/icon_shop_search_gray_fill.png'),
    shopMyPageFillGray: require('../assets/images/icon/icon_shop_my_gray_fill.png'),
    starYellow: require('../assets/images/icon/icon_star_yellow.png'),
    starGray: require('../assets/images/icon/icon_star_gray.png'),
    speechGray: require('../assets/images/icon/icon_speech_gray.png'),
    starHalfYellow: require('../assets/images/icon/icon_star_half_yellow.png'),
    visibleGray: require('../assets/images/icon/icon_visible_gray.png'),
    invisibleGray: require('../assets/images/icon/icon_invisible_gray.png'),
    visibleWhite: require('../assets/images/icon/icon_visible_white.png'),
    invisibleWhite: require('../assets/images/icon/icon_invisible_white.png'),
    gradientGreen: require('../assets/images/icon/gradient_green.png'),
    checkWhite: require('../assets/images/icon/icon_check_white.png'),
  },
  logo: {
    jumpingBlack: require('../assets/images/logo/logo_jumping_black.png'),
    jumpingWhite: require('../assets/images/logo/logo_jumping_white.png'),
  },
  splash: {
    splash_001: require('../assets/images/splash/splash_001.png'),
  }
};

export default IMAGES; 